#!/usr/bin/env python3
"""
build_data.py — Merge the researched raw scholarship files into a single
data/scholarships.json used by the AbroadReady website.

This normalises fields, adds a numeric deadline month (deadlineMonthNum) so the
browser can compute "days left" and Open/Closing-soon status live, and writes a
small meta block (counts, generatedAt) the site uses for its stats.

Run:  python3 updater/build_data.py
"""
import json
import glob
import os
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW_DIR = os.path.join(ROOT, "js", "raw")
OUT = os.path.join(ROOT, "data", "scholarships.json")
OUT_JS = os.path.join(ROOT, "js", "scholarships-data.js")

MONTHS = {
    "january": 1, "february": 2, "march": 3, "april": 4, "may": 5, "june": 6,
    "july": 7, "august": 8, "september": 9, "october": 10, "november": 11,
    "december": 12,
}

# Broad field buckets used by the results-page "Field" filter. Each scholarship
# is tagged with any bucket its listed fields map into (plus "All fields").
FIELD_BUCKETS = {
    "Engineering & Tech": ["engineer", "technology", "computer", "data science", "science & technology"],
    "Natural & Life Sciences": ["science", "biology", "health", "life science", "natural", "environment", "agricultur", "mathematic"],
    "Business & Economics": ["business", "econom", "management", "finance", "administration"],
    "Social Sciences & Law": ["social", "law", "political", "development", "education", "public health", "regional", "urban"],
    "Arts & Humanities": ["humanities", "media", "art", "music", "dance"],
}


def field_tags(fields):
    if not fields:
        return ["All fields"]
    joined = " ".join(fields).lower()
    if "all fields" in joined:
        return ["All fields"]
    tags = []
    for bucket, keys in FIELD_BUCKETS.items():
        if any(k in joined for k in keys):
            tags.append(bucket)
    if not tags:
        tags = ["Other / Specialised"]
    return tags


def main():
    scholarships = []
    seen = set()
    for path in sorted(glob.glob(os.path.join(RAW_DIR, "raw*.json"))):
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
        for s in data.get("scholarships", []):
            sid = s.get("id")
            if not sid or sid in seen:
                continue
            seen.add(sid)

            # Numeric deadline month for live status computation
            dm = s.get("deadlineMonth")
            s["deadlineMonthNum"] = MONTHS.get(dm.lower()) if isinstance(dm, str) else None

            # Field buckets for filtering
            s["fieldTags"] = field_tags(s.get("fields", []))

            # Normalise application fee into a simple boolean the UI can badge
            fee = (s.get("applicationFee") or "").strip().lower()
            s["isFree"] = fee in ("", "free", "none", "no fee", "0")

            scholarships.append(s)

    # Sort alphabetically by name for a stable default order
    scholarships.sort(key=lambda x: x.get("name", "").lower())

    countries = sorted({s["country"] for s in scholarships})
    regions = sorted({s["region"] for s in scholarships})

    out = {
        "meta": {
            "generatedAt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "count": len(scholarships),
            "countryCount": len(countries),
            "regions": regions,
            "note": "Deadlines are typical annual windows. The website recomputes the "
                    "next occurrence and days-left live in the browser. Always confirm "
                    "exact dates on the official apply link before applying.",
        },
        "scholarships": scholarships,
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(out, fh, ensure_ascii=False, indent=2)

    # Also emit a JS version so the site works when opened directly from disk
    # (file://) without a server, where fetch() of a local JSON is blocked.
    os.makedirs(os.path.dirname(OUT_JS), exist_ok=True)
    with open(OUT_JS, "w", encoding="utf-8") as fh:
        fh.write("/* Auto-generated by updater/build_data.py — do not edit by hand. */\n")
        fh.write("window.SCHOLARSHIP_DATA = ")
        json.dump(out, fh, ensure_ascii=False, indent=2)
        fh.write(";\n")

    print(f"Wrote {len(scholarships)} scholarships -> {OUT}")
    print(f"Also wrote JS data -> {OUT_JS}")
    print(f"Countries: {len(countries)} | Regions: {', '.join(regions)}")


if __name__ == "__main__":
    main()
