import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const RAW_DIR = join(ROOT, 'js', 'raw');
const OUT = join(ROOT, 'data', 'scholarships.json');
const OUT_JS = join(ROOT, 'js', 'scholarships-data.js');
const VERSION_FILE = join(ROOT, 'data', 'version.json');

const MONTHS = {
  january: 1, february: 2, march: 3, april: 4, may: 5, june: 6,
  july: 7, august: 8, september: 9, october: 10, november: 11, december: 12,
};

const FIELD_BUCKETS = {
  "Engineering & Tech": ["engineer", "technology", "computer", "data science", "science & technology"],
  "Natural & Life Sciences": ["science", "biology", "health", "life science", "natural", "environment", "agricultur", "mathematic"],
  "Business & Economics": ["business", "econom", "management", "finance", "administration"],
  "Social Sciences & Law": ["social", "law", "political", "development", "education", "public health", "regional", "urban"],
  "Arts & Humanities": ["humanities", "media", "art", "music", "dance"],
};

function fieldTags(fields) {
  if (!fields || fields.length === 0) return ["All fields"];
  const joined = fields.join(" ").toLowerCase();
  if (joined.includes("all fields")) return ["All fields"];
  const tags = [];
  for (const [bucket, keys] of Object.entries(FIELD_BUCKETS)) {
    if (keys.some(k => joined.includes(k))) tags.push(bucket);
  }
  return tags.length ? tags : ["Other / Specialised"];
}

function main() {
  const scholarships = [];
  const seen = new Set();

  const rawFiles = readdirSync(RAW_DIR)
    .filter(f => f.endsWith('.json'))
    .sort();

  for (const file of rawFiles) {
    const data = JSON.parse(readFileSync(join(RAW_DIR, file), 'utf-8'));
    for (const s of (data.scholarships || [])) {
      const sid = s.id;
      if (!sid || seen.has(sid)) continue;
      seen.add(sid);

      const dm = s.deadlineMonth;
      if (typeof dm === 'string') {
        s.deadlineMonthNum = MONTHS[dm.toLowerCase()] ?? null;
      } else {
        s.deadlineMonthNum = null;
      }

      const om = s.opensMonth;
      if (typeof om === 'string') {
        s.opensMonthNum = MONTHS[om.toLowerCase()] ?? null;
      } else {
        s.opensMonthNum = null;
      }

      s.fieldTags = fieldTags(s.fields);
      const fee = (s.applicationFee || '').toString().trim().toLowerCase();
      s.isFree = ['', 'free', 'none', 'no fee', '0'].includes(fee);

      scholarships.push(s);
    }
  }

  scholarships.sort((a, b) => (a.name || '').toLowerCase().localeCompare((b.name || '').toLowerCase()));

  const countries = [...new Set(scholarships.map(s => s.country))].sort();
  const regions = [...new Set(scholarships.map(s => s.region))].sort();

  const metaNote = "Deadlines are typical annual windows. The website recomputes the next occurrence and days-left live in the browser. Always confirm exact dates on the official apply link before applying.";

  const out = {
    meta: {
      generatedAt: new Date().toISOString().replace(/\.\d{3}Z$/, 'Z'),
      count: scholarships.length,
      countryCount: countries.length,
      regions,
      note: metaNote,
    },
    scholarships,
  };

  const dir = dirname(OUT);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  writeFileSync(OUT, JSON.stringify(out, null, 2), 'utf-8');
  writeFileSync(OUT_JS, `/* Auto-generated by updater/build_data.mjs */\nwindow.SCHOLARSHIP_DATA = ${JSON.stringify(out, null, 2)};\n`, 'utf-8');

  let build = 1;
  try {
    const existing = JSON.parse(readFileSync(VERSION_FILE, 'utf-8'));
    build = (existing.build || 0) + 1;
  } catch (e) { /* first build */ }
  const versionData = {
    build,
    date: new Date().toISOString().replace(/\.\d{3}Z$/, 'Z'),
  };
  writeFileSync(VERSION_FILE, JSON.stringify(versionData, null, 2), 'utf-8');

  console.log(`Wrote ${scholarships.length} scholarships -> ${OUT}`);
  console.log(`Also wrote JS data -> ${OUT_JS}`);
  console.log(`Countries: ${countries.length} | Regions: ${regions.join(', ')}`);
  console.log(`Build #${build} -> ${VERSION_FILE}`);
}

main();
